name: Integrate

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 22 is in Maintenance until April 2027.
        # 24 is Active until October 2026, Maintenance until April 2028.
        # 26 is Current from May 2026 to October 2026, then Active until October 2027, Maintenance until April 2029.
        # 28 will be Current in April/May 2027.
        # https://nodejs.org/en/about/previous-releases
        #
        # 24.16 and 26 cause problems with webdriverio, sticking to working versions for now.
        # Monitor https://github.com/webdriverio/webdriverio/issues/15265 for updates
        # on Webdriver side.
        node-version: [22, 24.15]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Disable AppArmor on ubuntu
        # Security on Ubuntu ⩾ 23 causes problem with Chrome, this is copied from
        # https://github.com/puppeteer/puppeteer/blob/main/.github/workflows/ci.yml
        # where they probably know what they do.
        #       if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - run: yarn install --immutable

      - name: Install Playwright browsers
        # https://playwright.dev/docs/ci-intro
        run: yarn playwright install

      - run: yarn dedupe --check
      - run: yarn build
      - run: yarn test
      - run: yarn knip
